name: SentimentAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - _pytorch_select=0.1
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=35.0.0
  - dataclasses=0.8
  - filelock=3.3.2
  - huggingface_hub=0.1.2
  - idna=3.1
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2019.4
  - joblib=1.1.0
  - libcxx=12.0.0
  - libffi=3.3
  - libmklml=2019.0.5
  - llvm-openmp=12.0.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1l
  - packaging=21.0
  - pip=21.2.2
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pysocks=1.7.1
  - python=3.7.11
  - python_abi=3.7
  - pytorch=1.7.1
  - pyyaml=6.0
  - readline=8.1
  - regex=2021.11.10
  - requests=2.26.0
  - sacremoses=0.0.46
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - tokenizers=0.10.3
  - tqdm=4.62.3
  - transformers=4.12.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
