name: TwitterAccordNetwork
channels:
  - conda-forge
  - Microsoft
  - defaults
dependencies:
  - aiohttp=3.7.4.post0
  - async-timeout=3.0.1
  - attrs=21.2.0
  - azure-ai-textanalytics=2021.09.01
  - azure-core=2021.09.01
  - azure-identity=2021.09.01
  - blas=1.0
  - blinker=1.4
  - boto=2.49.0
  - boto3=1.18.21
  - botocore=1.21.41
  - brotlipy=0.7.0
  - bz2file=0.98
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=35.0.0
  - cython=0.29.23
  - gensim=4.0.1
  - idna=3.2
  - intel-openmp=2021.4.0
  - isodate=0.6.0
  - jmespath=0.10.0
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.0
  - libzlib=1.2.11
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msal=2021.09.01
  - msal-extensions=2021.09.01
  - msrest=2021.09.01
  - multidict=5.1.0
  - ncurses=6.3
  - networkx=2.6.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.1.1
  - openssl=1.1.1l
  - pip=21.2.4
  - portalocker=2.3.0
  - pycparser=2.20
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-dotenv=0.19.1
  - python_abi=3.8
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - s3transfer=0.5.0
  - scipy=1.7.1
  - setuptools=58.0.4
  - six=1.16.0
  - smart_open=1.9.0
  - sqlite=3.36.0
  - tk=8.6.11
  - tqdm=4.62.3
  - tweepy=4.2.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wheel=0.37.0
  - xz=5.2.5
  - yarl=1.6.3
  - zlib=1.2.11
